export const estudantes = [
  "ALEXANDRE LEMOS ALVES FILHO",
  "ANA GRAÇA SPIER STOFFEL",
  "ÁDRIAN FEIJÓ FAGUNDES",
  "ARIEL LORENZ",
  "ARTHUR DE SOUZA MANSKE",
  "EMANUEL VICTOR CHAVES",
  "FELIPE CANTINI",
  "GUILHERME MORAES KELLER",
  "GUSTAVO HENRIQUE DE OLIVEIRA",
  "GUSTAVO RIBEIRO DA SILVA",
  "JEANDERSON LEDUR",
  "LEANDRO HENRIQUE SANTOS GUARINIRI",
  "LEONARDO ESLABÃO BARBOSA COSTA",
  "LUCAS MACHADO FLORÃO",
  "LUIJI ARTHUR KINOSHITA DA CRUZ",
  "MARIA EDUARDA COSTA BATISTA DOS SANTOS",
  "MARIANA SANTOS BAZOTTO DA SILVA",
  "MATHEUS BRAGA MATTOS",
  "NATAN GABRIEL WILDNER DA SILVA",
  "PEDRO HENRIQUE NUNES CARLOS",
  "ROGERIO FERNANDO MACHADO",
  "STEVÃO SEVERO RODRIGUES",
  "YAGO DOS SANTOS E SOUZA",
];


export const atividadesFallback = [
  { id: 1, titulo: "Atividade 1", descricao: "" },
  { id: 2, titulo: "Atividade 2", descricao: "" },
  { id: 3, titulo: "Atividade 3", descricao: "" },
]
